export default {
    FETCH_ALL_DATA : "FETCH ALL DATA",
    FILTER_BY_PRICE : "FILTER BY PRICE",
    TOGGLE_FILTER : "TOGGLE FILTER APPLIED",
    FILTER_BY_PRICE: "ByPrice",
    FILTER_BY_SPACE : "BySpace",
    FILTER_BY_SIGN : "ByCity",
    FILTER_BY_PRICE_ASC : "FILTER PRICE BY ASC",
    COPY_DEFAULT_DATA : "COPY DEFAULT DATA"
}