export default {
    //ListFullData
    FETCH_ALL_DATA : "FETCH ALL DATA",
    //FilterData
    APPLY_FILTER_OPTIONS : "APPLY FILTER OPTIONS",
    FILTER_BY_PRICE: "ByPrice",
    FILTER_BY_SPACE : "BySpace",
    FILTER_BY_CITY : "ByCity",
    COPY_DEFAULT_DATA : "COPY DEFAULT DATA",
    SET_UPDATED_DATA : "SET UPDATED DATA",
    REMOVE_FILTERS : "REMOVE FILTER"
}